# Question 1.

# Can you explain the following code (10)

In [1]:
import numpy as np

inputs = np.array(
   [[0.43, 0.15, 0.89], # Your
    [0.55, 0.87, 0.66], # journey
    [0.57, 0.85, 0.64], # starts
    [0.22, 0.58, 0.33], # with
    [0.77, 0.25, 0.10], # one 
    [0.05, 0.80, 0.55]] # step
)

print(inputs.shape)
print()
print(inputs.shape[0])
print()
query = inputs[1]

attn_scores_2 = np.empty(inputs.shape[0])

for i, x_i in enumerate(inputs):
    attn_scores_2[i] = np.dot(x_i, query)
print(attn_scores_2)

(6, 3)

6

[0.9544 1.495  1.4754 0.8434 0.707  1.0865]


# Question 2.

# Can you explain the following code (5)

In [2]:
import numpy as np

inputs = np.array(
   [[0.43, 0.15, 0.89], # Your
    [0.55, 0.87, 0.66], # journey
    [0.57, 0.85, 0.64], # starts
    [0.22, 0.58, 0.33], # with
    [0.77, 0.25, 0.10], # one 
    [0.05, 0.80, 0.55]] # step
)

query = inputs[1]

attn_scores_2 = np.empty(inputs.shape[0])

for i, x_i in enumerate(inputs):
    attn_scores_2[i] = np.dot(x_i, query)
print(attn_scores_2)

attn_weights_2_tmp = attn_scores_2 / attn_scores_2.sum()

print()
print(attn_weights_2_tmp)
print()
print(attn_weights_2_tmp.sum())

[0.9544 1.495  1.4754 0.8434 0.707  1.0865]

[0.14545011 0.2278373  0.22485027 0.12853376 0.10774647 0.16558209]

1.0


# Question 3.

# Can you explain the following code. Why inputs @ inputs.T is better than dot product from for loop? (10)

In [3]:
import numpy as np

inputs = np.array(
   [[0.43, 0.15, 0.89], # Your
    [0.55, 0.87, 0.66], # journey
    [0.57, 0.85, 0.64], # starts
    [0.22, 0.58, 0.33], # with
    [0.77, 0.25, 0.10], # one 
    [0.05, 0.80, 0.55]] # step
)

attn_scores = np.empty((inputs.shape[0], inputs.shape[0]))

for i, x_i in enumerate(inputs):
    for j, x_j in enumerate(inputs):
        attn_scores[i, j] = np.dot(x_i, x_j)
        
print(attn_scores)

[[0.9995 0.9544 0.9422 0.4753 0.4576 0.631 ]
 [0.9544 1.495  1.4754 0.8434 0.707  1.0865]
 [0.9422 1.4754 1.457  0.8296 0.7154 1.0605]
 [0.4753 0.8434 0.8296 0.4937 0.3474 0.6565]
 [0.4576 0.707  0.7154 0.3474 0.6654 0.2935]
 [0.631  1.0865 1.0605 0.6565 0.2935 0.945 ]]


# Above dot product is very slow because we have nested for loop which has a big O complexity of O(n^2)

In [4]:
import numpy as np

inputs = np.array(
   [[0.43, 0.15, 0.89], # Your
    [0.55, 0.87, 0.66], # journey
    [0.57, 0.85, 0.64], # starts
    [0.22, 0.58, 0.33], # with
    [0.77, 0.25, 0.10], # one 
    [0.05, 0.80, 0.55]] # step
)

attn_scores = inputs @ inputs.T
        
print(attn_scores)

[[0.9995 0.9544 0.9422 0.4753 0.4576 0.631 ]
 [0.9544 1.495  1.4754 0.8434 0.707  1.0865]
 [0.9422 1.4754 1.457  0.8296 0.7154 1.0605]
 [0.4753 0.8434 0.8296 0.4937 0.3474 0.6565]
 [0.4576 0.707  0.7154 0.3474 0.6654 0.2935]
 [0.631  1.0865 1.0605 0.6565 0.2935 0.945 ]]


# The above matrix multiplication is handled by numpy is very fast.
# Vectorized Operation:

# The @ operator (or np.dot for matrix multiplication) is a vectorized operation. It is implemented in highly optimized C and Fortran libraries (e.g., BLAS, LAPACK) that are designed to perform matrix operations efficiently.

# Single Function Call:

# The entire matrix multiplication is computed in a single function call, avoiding the overhead of repeatedly calling np.dot in a loop.

# Parallelization:

# NumPy’s underlying libraries can take advantage of multi-threading and SIMD (Single Instruction, Multiple Data) instructions on modern CPUs, allowing the computation to be parallelized and executed much faster.

# Memory Efficiency:

# The operation is performed on entire arrays at once, which is more cache-friendly and reduces memory access overhead.

# Question 4.

# What is following code doing please explain (2.5)

In [5]:
import numpy as np

# Define the array
array = np.array(
    [[0.9995, 0.9544, 0.9422, 0.4753, 0.4576, 0.631 ],
     [0.9544, 1.495 , 1.4754, 0.8434, 0.707 , 1.0865],
     [0.9422, 1.4754, 1.457 , 0.8296, 0.7154, 1.0605],
     [0.4753, 0.8434, 0.8296, 0.4937, 0.3474, 0.6565],
     [0.4576, 0.707 , 0.7154, 0.3474, 0.6654, 0.2935],
     [0.631 , 1.0865, 1.0605, 0.6565, 0.2935, 0.945 ]]
)

# Sum across the column axis (axis=0)
column_sums = np.sum(array, axis=0)

print(column_sums)

[4.46   6.5617 6.4801 3.6459 3.1863 4.673 ]


# Question 5.

# What is following code doing please explain (2.5)

In [6]:
import numpy as np
np.random.seed(42)  # Set a seed for reproducibility


# Define the array
random_matrix = np.random.rand(6, 6).round(2)
print(random_matrix)

rows_sums = np.sum(random_matrix, axis=1)

print("\n\n\n")
print(rows_sums)

[[0.37 0.95 0.73 0.6  0.16 0.16]
 [0.06 0.87 0.6  0.71 0.02 0.97]
 [0.83 0.21 0.18 0.18 0.3  0.52]
 [0.43 0.29 0.61 0.14 0.29 0.37]
 [0.46 0.79 0.2  0.51 0.59 0.05]
 [0.61 0.17 0.07 0.95 0.97 0.81]]




[2.97 3.23 2.22 2.13 2.6  3.58]


# Question 6.

# Can you explain the np.tril function. Where do you think this will be used? (10)

In [7]:
import numpy as np
np.random.seed(42)  # Set a seed for reproducibility


# Define the array
random_matrix = np.random.rand(6, 6).round(2)
print("Original matrix:")
print(random_matrix)
print()

# Extract the lower triangular part (default: k=0)
lower_triangular = np.tril(random_matrix)


print("\nLower triangular matrix:")
print(lower_triangular)
print()

# Replace all zeros with -inf
lower_triangular[lower_triangular == 0] = -np.inf
print("\n 0's are replaced with -inf")
print(lower_triangular)

Original matrix:
[[0.37 0.95 0.73 0.6  0.16 0.16]
 [0.06 0.87 0.6  0.71 0.02 0.97]
 [0.83 0.21 0.18 0.18 0.3  0.52]
 [0.43 0.29 0.61 0.14 0.29 0.37]
 [0.46 0.79 0.2  0.51 0.59 0.05]
 [0.61 0.17 0.07 0.95 0.97 0.81]]


Lower triangular matrix:
[[0.37 0.   0.   0.   0.   0.  ]
 [0.06 0.87 0.   0.   0.   0.  ]
 [0.83 0.21 0.18 0.   0.   0.  ]
 [0.43 0.29 0.61 0.14 0.   0.  ]
 [0.46 0.79 0.2  0.51 0.59 0.  ]
 [0.61 0.17 0.07 0.95 0.97 0.81]]


 0's are replaced with -inf
[[0.37 -inf -inf -inf -inf -inf]
 [0.06 0.87 -inf -inf -inf -inf]
 [0.83 0.21 0.18 -inf -inf -inf]
 [0.43 0.29 0.61 0.14 -inf -inf]
 [0.46 0.79 0.2  0.51 0.59 -inf]
 [0.61 0.17 0.07 0.95 0.97 0.81]]


# Question 7

# What is the following program doing can you explain it. (10)

In [8]:
import numpy as np

# Create a 3D array (batch_size=3, sequence_length=4, num_classes=5)
logits = np.array([
    # Batch 1
    [[0.1, 0.2, 0.3, 0.4, 0.5],
     [0.6, 0.7, 0.8, 0.9, 1.0],
     [1.1, 1.2, 1.3, 1.4, 1.5],
     [1.6, 1.7, 1.8, 1.9, 2.0]],

    # Batch 2
    [[2.1, 2.2, 2.3, 2.4, 2.5],
     [2.6, 2.7, 2.8, 2.9, 3.0],
     [3.1, 3.2, 3.3, 3.4, 3.5],
     [3.6, 3.7, 3.8, 3.9, 4.0]],

    # Batch 3
    [[4.1, 4.2, 4.3, 4.4, 4.5],
     [4.6, 4.7, 4.8, 4.9, 5.0],
     [5.1, 5.2, 5.3, 5.4, 5.5],
     [5.6, 5.7, 5.8, 5.9, 6.0]]
])

# Extract the logits for the last token in each sequence
last_token_logits = logits[:, -1, :]

print("Original logits shape:", logits.shape)
print("Last token logits shape:", last_token_logits.shape)
print("\nLast token logits:")
print(last_token_logits)

Original logits shape: (3, 4, 5)
Last token logits shape: (3, 5)

Last token logits:
[[1.6 1.7 1.8 1.9 2. ]
 [3.6 3.7 3.8 3.9 4. ]
 [5.6 5.7 5.8 5.9 6. ]]
