**Question 1**

In [6]:
import re

String123 = 'Hello 1 World 2'

print(re.sub(r'[aeiouAEIOU]','',String123))

Hll 1 Wrld 2


**Question 2**

In [7]:
L = ['a','b','c']
print('-'.join(L))

a-b-c


**Question 3**

In [8]:
q3 = 'hello world'
print(q3[::-1])

dlrow olleh


Question 4

In [10]:
def is_anagram(s1,s2):
    #Sort characters of list in ascending order and compare, if equal then return True
    return sorted(s1) == sorted(s2)

print(is_anagram('listen','silenti'))
print(is_anagram('listen','silent'))

False
True


**Question 5**

In [15]:
string = 'this is assignment 1 for my NLP class'
print(string.split())
print(string.split('a'))
print(string.split('i'))

['this', 'is', 'assignment', '1', 'for', 'my', 'NLP', 'class']
['this is ', 'ssignment 1 for my NLP cl', 'ss']
['th', 's ', 's ass', 'gnment 1 for my NLP class']


**Question 6**

In [17]:
mystring = '                     hi how are you                      '
mystring.lstrip()
#Removes spaces from left side of string

'hi how are you                      '

In [18]:
mystring.rstrip()
#Removes spaces from right side of string

'                     hi how are you'

In [19]:
mystring.strip()
#Removes spaces from both sides of string

'hi how are you'

**Question 7**

In [20]:
mystring = 'hello how are you'
mystring.title()

'Hello How Are You'

**Question 8**

In [22]:
from tabulate import tabulate

data = [
    ["List", "Yes", "No"],
    ["Dictionary", "Yes", "No"],
    ["Set", "Yes", "No"],
    ["User-defined classes", "Yes", "Yes"],
    ["Int, float, decimal, bool", "No", "Yes"],
    ["String", "No", "Yes"],
    ["Tuple", "No", "Yes"]
]
print(tabulate(data, headers=["Datatype", "Mutable", "Immutable"], tablefmt="grid"))

+---------------------------+-----------+-------------+
| Datatype                  | Mutable   | Immutable   |
+===========================+===========+=============+
| List                      | Yes       | No          |
+---------------------------+-----------+-------------+
| Dictionary                | Yes       | No          |
+---------------------------+-----------+-------------+
| Set                       | Yes       | No          |
+---------------------------+-----------+-------------+
| User-defined classes      | Yes       | Yes         |
+---------------------------+-----------+-------------+
| Int, float, decimal, bool | No        | Yes         |
+---------------------------+-----------+-------------+
| String                    | No        | Yes         |
+---------------------------+-----------+-------------+
| Tuple                     | No        | Yes         |
+---------------------------+-----------+-------------+


**Question 9**

*Are lists mutable in python?*
Lists can be modified and values can be updated, therefore lists are mutable in python.

**Question 10**

*Are strings mutable in python?* Strings cannot be updated, as 'updating' a string actually only creates a new string object, not changing the original.

**Question 11**

In [24]:
names = ['Mukesh', 'Roni', 'Charti']
ages = [25, 50, 18]

for i, (name, age) in enumerate(zip(names, ages)):
    print(i, name, age)

0 Mukesh 25
1 Roni 50
2 Charti 18


In [25]:
k = list(zip(names, ages))
print(k)

[('Mukesh', 25), ('Roni', 50), ('Charti', 18)]


**Question 12**

In [26]:
pets = ['dog','cat','guinea pig', 'parrot']
numbers = [2,4,10,2]
pet_numbers_dict = {}
for animal,num in zip(pets,numbers):
    pet_numbers_dict[animal] = num
print(pet_numbers_dict)

##The program uses zip and two lists to create a dictionary, associating each pet key with a number value.

{'dog': 2, 'cat': 4, 'guinea pig': 10, 'parrot': 2}


**Question 13**

In [27]:
GEEK = {'g','e','k'}
GEEK.add('s')
print("Letters are:", GEEK)

GEEK.add('s')
print("Letters are:", GEEK)

Letters are: {'e', 's', 'g', 'k'}
Letters are: {'e', 's', 'g', 'k'}


**Question 14**

In [4]:
def is_prime(num):
    notPrime = False
    if num <= 1:
        print(str(num) + " is not a prime number.")
    elif num == 2:
        print(str(num) + " is a prime number.")
    for i in range(2, int(num ** 0.5) + 1):
        if num % i == 0:
            notPrime = True
            print(str(num) + " is not a prime number.")
            break
    if notPrime == False:
        print(str(num) + " is a prime number.")  


is_prime(8)
is_prime(7)

8 is not a prime number.
7 is a prime number.


**Question 15**

In [5]:
def fib_series(n):
    a, b = 0, 1
    for i in range(n):
        print(a, end=" ")
        a, b = b, a + b

n = 10
fib_series(n)

0 1 1 2 3 5 8 13 21 34 

**Question 16**

In [11]:
from urllib import request
import nltk
from nltk.probability import FreqDist

url = "https://rest.uniprot.org/uniprotkb/P17181.fasta"
response = request.urlopen(url)
fasta = response.read().decode('utf8')

sequence = ''.join(fasta.splitlines()[1:])

amino_acids = 'ARNDCEQGHILKMFPSTWYV'
freq_dist = FreqDist(sequence)

amino_counts = {}
for indiv_amino in amino_acids:
    amino_counts[indiv_amino] = freq_dist[indiv_amino]

for indiv_amino, count in amino_counts.items():
    print(f"{indiv_amino} = {count}")

A = 27
R = 13
N = 35
D = 25
C = 11
E = 42
Q = 23
G = 19
H = 9
I = 43
L = 43
K = 44
M = 6
F = 26
P = 26
S = 51
T = 36
W = 13
Y = 22
V = 43


**Question 17**

One hot encoding is a technique for converting categorical variables to a numerical format, where you have a matrix(dataset) of categorical variables, and rows indicating one(it is the label) and zero(it is not the label). So for labels such as red, gren and yellow, a one hot encoded red value would be [1,0,0].

One hot encoding is used to encode the amino acid sequences by assigning encoded values to the amino sequences. If A encoded is [1,0,0,...,0], P is encoded [0,0,1,...,0], and D is encoded [0,1,0,...,0] then a sequence of APD is encoded as [[1,0,0,...,0],[0,0,1,...,0],[0,1,0,...,0]]

It's advantages are that it is effective for many ML models and maintains disctinction between different categorical variables while its disadvantages inlcude its high dimensionality(large vectors/matrices for many variables) and high memory usage(for large datasets).

If I were a data scientist, I would probably use one hot encoding in some of my projects depending on the use case. If I have a large amount of labels to be encoded, it would most likely be better for me to use a different form of encoding, as it might be hard to understand the encoded data and would take up much more memory than other methods.

In [5]:
import numpy as np

#Create a dictionary that maps each amino acid to an integer
aminoList = "ACDEFGHIKLMNPQRSTVWY"
aminoDict = {amino: i for i, amino in enumerate(aminoList)}
aminoDict

#Function that one-hot encodes a sequence
def one_hot_encode(sequence, aminoDict = aminoDict):
    #Create a matrix of zeros
    one_hot = np.zeros((len(sequence), len(aminoDict)))
    #Set the appropriate elements to 1
    for i, amino in enumerate(sequence):
        one_hot[i, aminoDict[amino]] = 1

    #Return the one-hot encoded sequence
    return one_hot

sequence = 'ACDGKINWE'
one_hot = one_hot_encode(sequence)
print(one_hot)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


**Question 18**

We convert words to integer values before passing to a model because neural networks and machine learning models operate on and process numerical data, not text data. This also reduces the complexity of models. Since computers dont inherently 'understand' words, we must convert the data to integer values in order to use models and algorithms to reach our end goal of what we wish to do with the data. Tokenizing the text and then converting those tokens into integer IDs allows us to process textual data.

**Question 19**

The code starts off with assigning a numpy array of feature vectors, each one associated (told to us through code comments) witha specific word. "Your" is assigned the feature vector of [0.43, 0.15, 0.89], for example. The code shows the shape of the array, which shows us that it has 6 words and 3 features identifying the words. The print(inputs.shape[0]) line just shows us how many words we have, which is 6. The query = inputs[1] assigns us a variable of "query" to [0.55, 0.87, 0.66] (which is the "journey" word's feature vector). The code then creates an attention scores array of size 6 (the number of words we have in our vocabulary). The code then iterates over each feature vector in the inputs array and calculates an attention score (dot product of the the iterated and the query feature vectors) for each of the feature vectors. The attention score represents the similarity between each word's feature vector in the vocabulary and the query word(the higher the attention score, the more similar it is to the query word's feature vector).

**Question 20**

This code is similar to the code from question 20, however *while the code above only calculates the attention scores of each word compared to a query, this code computes the attention scores of each word compared to a query and then normalizes it into an attention weight by dividing each attention scores by the sum of all the attention scores.* Normalization is important because it allows the attention weights to contribute more to the final output if the weight is higher. This program also displays that the sum of all attention weights is 1(which makes sense since the weights are meant to function like a weighted average or a weighted percentage).

**Question 21**

This code is also similar to question 19's code, however while the code from question 19 only calculates the attention score for a query word and the words in the inputs array, *this code calculates the attention scores of each possible word pair in the inputs vocabulary, making it more useful for an attention score driven model.* Attention score is, as I mentioned before, calculated by performing the dot product of two words' feature vectors.

in the second code snippet, the code uses *inputs @ inputs.T* to calculate the attention score matrix, which is better than dot product because the time complexity of a nested for loop is O(n^2). The @ operator is a matrix multiplication operator and is inherently faster than using a manual for loop for the calculation.

**Question 22**

The first code snippet has an output of [4.46   6.5617 6.4801 3.6459 3.1863 4.673 ], which is the sum of each column printed as a vector. The code is taking a 6x6 matrix and calculating the sum of each column, and saving it to a vector.

The second code snippet is creating a 6x6 matrix of random values between 0 and 1, with 2 decimal places, and summing each row and storing it in a vector. The outputs are the random matrix, and the vector of each row's sum.

**Question 23**

The code snippet shows a usage of the np.tril function, which takes a matrix and sets all values above and to the right of the diagonal to 0(it keeps the values along the diagonal). We also see the code set all values that were set to 0 by the tril function to -inf. This technique can and is used in NLP during model training, so that the model does not look ahead in the tokens when training the model, as we need it to be predicting a future token using tokens it has, not using tokens it already knows is there.

**Question 24**

The code provided creates a 3D array of 3 batches of logits(raw output of a NN model). Often, the NN's final output is the last token's logits. The *last_token_logits = logits[:, -1, :]* line extracts the last logit vector in each batch, and adds it to an array named "last_token_logits". This is being done to extract (presumably a NN's output) from the rest of the logits, essentially extracting the model's final output tokens. The program then prints the original shape, the last token logits shape, and prints the values in the last token logits array.