In [1]:
import pandas as pd
import numpy as np

df_training = pd.read_csv("Glycobiology_NGlyDE_Training_Positive_1821_Negative_901.csv",header=None)

In [2]:
df_training

0       1     2                          3    4         5         6     \
0        1  A6NH11   276  LVRAAGTLEDVYNRTQSLLAERGLL    N -0.299127 -0.199549   
1        1  A6NMZ7   198  LRTVRDLSMFSQNMTHIIKDVIKYK    N -0.091352 -0.038519   
2        1  A6NMZ7   275  ENCMRVGLVAYSNETKVINSLSMGI    N -0.307903 -0.092990   
3        1  A6NMZ7   288  ETKVINSLSMGINKSEVLQHIQNLS    N -0.515774 -0.117307   
4        1  A6NMZ7   298  GINKSEVLQHIQNLSPRTGKAYTGA    N -0.085012 -0.047289   
...    ...     ...   ...                        ...  ...       ...       ...   
2717     0  Q9UBG0   102  TMQCLGTGWPGTNTTASLGMYECDR    N -0.202173 -0.066933   
2718     0  Q9UBG0   492  DCVTIWGPEGRWNDSPCNQSLPSIC    N  0.114712  0.265292   
2719     0  Q9UBG0   497  WGPEGRWNDSPCNQSLPSICKKAGQ    N -0.098298  0.070397   
2720     0  Q9UBG0   634  ATGSAMGLWEVKNCTSFRARYICRQ    N -0.160428  0.112416   
2721     0  Q9UBG0  1134  LPPAPGTELSYLNGTFRLLQKPLRW    N -0.186085 -0.244415   

          7         8         9     ...      1019      1020      1021  \
0    -0.179856 -0.157317  0.337936  ... -0.327789 -0.314218  0.321511   
1    -0.057120  0.159410  0.160944  ... -0.432134 -0.259395  0.138881   
2    -0.176675  0.009118  0.118984  ...  0.168333 -0.305920  0.260424   
3    -0.022314  0.068052  0.066636  ... -0.210106 -0.110623 -0.105524   
4    -0.057903  0.007610 -0.087651  ...  0.022734 -0.138056 -0.243995   
...        ...       ...       ...  ...       ...       ...       ...   
2717 -0.137959  0.014744 -0.007213  ... -0.316318 -0.186689  0.317165   
2718 -0.172495  0.228116  0.045399  ... -0.203411 -0.494579 -0.181199   
2719 -0.094826  0.081707  0.209689  ... -0.448132 -0.075102  0.066447   
2720 -0.302477 -0.247829 -0.089747  ... -0.388438 -0.177720 -0.154067   
2721  0.127036 -0.137570 -0.066978  ...  0.022763 -0.071848  0.196073   

          1022      1023      1024      1025      1026      1027      1028  
0    -0.250782  0.169454  0.001813 -0.181462  0.050026  0.545563  0.303575  
1    -0.152130  0.063748 -0.387179 -0.014736  0.214407  0.495020  0.105730  
2    -0.181876  0.117701 -0.352875 -0.121876  0.405135  0.401849  0.373381  
3    -0.216135  0.154849 -0.063129 -0.085552  0.069067  0.501313  0.280559  
4    -0.013408  0.174836  0.263506  0.024929  0.011373  0.148401 -0.072135  
...        ...       ...       ...       ...       ...       ...       ...  
2717 -0.192757  0.260818 -0.433473 -0.015665  0.115081  0.359386  0.477398  
2718  0.075058  0.100884 -0.175777 -0.015447  0.170279  0.111317  0.134552  
2719 -0.200532  0.038641 -0.249197 -0.257202  0.165700  0.269885  0.301271  
2720 -0.042331  0.113914 -0.072617 -0.059681  0.408955  0.329044  0.212268  
2721  0.074072  0.043421 -0.194287  0.107536  0.155424  0.119035  0.064604  

[2722 rows x 1029 columns]

In [3]:
df_training.columns = ["Label","PID","Position","Peptide","ASN"]+[int(i) for i in range(1,1025)]

In [4]:
df_training

Label     PID  Position                    Peptide ASN         1  \
0         1  A6NH11       276  LVRAAGTLEDVYNRTQSLLAERGLL   N -0.299127   
1         1  A6NMZ7       198  LRTVRDLSMFSQNMTHIIKDVIKYK   N -0.091352   
2         1  A6NMZ7       275  ENCMRVGLVAYSNETKVINSLSMGI   N -0.307903   
3         1  A6NMZ7       288  ETKVINSLSMGINKSEVLQHIQNLS   N -0.515774   
4         1  A6NMZ7       298  GINKSEVLQHIQNLSPRTGKAYTGA   N -0.085012   
...     ...     ...       ...                        ...  ..       ...   
2717      0  Q9UBG0       102  TMQCLGTGWPGTNTTASLGMYECDR   N -0.202173   
2718      0  Q9UBG0       492  DCVTIWGPEGRWNDSPCNQSLPSIC   N  0.114712   
2719      0  Q9UBG0       497  WGPEGRWNDSPCNQSLPSICKKAGQ   N -0.098298   
2720      0  Q9UBG0       634  ATGSAMGLWEVKNCTSFRARYICRQ   N -0.160428   
2721      0  Q9UBG0      1134  LPPAPGTELSYLNGTFRLLQKPLRW   N -0.186085   

             2         3         4         5  ...      1015      1016  \
0    -0.199549 -0.179856 -0.157317  0.337936  ... -0.327789 -0.314218   
1    -0.038519 -0.057120  0.159410  0.160944  ... -0.432134 -0.259395   
2    -0.092990 -0.176675  0.009118  0.118984  ...  0.168333 -0.305920   
3    -0.117307 -0.022314  0.068052  0.066636  ... -0.210106 -0.110623   
4    -0.047289 -0.057903  0.007610 -0.087651  ...  0.022734 -0.138056   
...        ...       ...       ...       ...  ...       ...       ...   
2717 -0.066933 -0.137959  0.014744 -0.007213  ... -0.316318 -0.186689   
2718  0.265292 -0.172495  0.228116  0.045399  ... -0.203411 -0.494579   
2719  0.070397 -0.094826  0.081707  0.209689  ... -0.448132 -0.075102   
2720  0.112416 -0.302477 -0.247829 -0.089747  ... -0.388438 -0.177720   
2721 -0.244415  0.127036 -0.137570 -0.066978  ...  0.022763 -0.071848   

          1017      1018      1019      1020      1021      1022      1023  \
0     0.321511 -0.250782  0.169454  0.001813 -0.181462  0.050026  0.545563   
1     0.138881 -0.152130  0.063748 -0.387179 -0.014736  0.214407  0.495020   
2     0.260424 -0.181876  0.117701 -0.352875 -0.121876  0.405135  0.401849   
3    -0.105524 -0.216135  0.154849 -0.063129 -0.085552  0.069067  0.501313   
4    -0.243995 -0.013408  0.174836  0.263506  0.024929  0.011373  0.148401   
...        ...       ...       ...       ...       ...       ...       ...   
2717  0.317165 -0.192757  0.260818 -0.433473 -0.015665  0.115081  0.359386   
2718 -0.181199  0.075058  0.100884 -0.175777 -0.015447  0.170279  0.111317   
2719  0.066447 -0.200532  0.038641 -0.249197 -0.257202  0.165700  0.269885   
2720 -0.154067 -0.042331  0.113914 -0.072617 -0.059681  0.408955  0.329044   
2721  0.196073  0.074072  0.043421 -0.194287  0.107536  0.155424  0.119035   

          1024  
0     0.303575  
1     0.105730  
2     0.373381  
3     0.280559  
4    -0.072135  
...        ...  
2717  0.477398  
2718  0.134552  
2719  0.301271  
2720  0.212268  
2721  0.064604  

[2722 rows x 1029 columns]

In [5]:
df_training["Label"].value_counts()

1    1821
0     901
Name: Label, dtype: int64

In [6]:
df_independent_testing = pd.read_csv("Independent_Test_Set_Prot_T5_feature_Aug_12.txt",header=None)

In [7]:
df_independent_testing

0       1     2                                          3    4     \
0       1  O00206    35  MAFLSCVRPESWEPCVEVVPNITYQCMELNFYKIPDNLPFS    N   
1       1  O00206   173  KELNVAHNLIQSFKLPEYFSNLTNLEHLDLSSNKIQSIYCT    N   
2       1  O00206   205  NKIQSIYCTDLRVLHQMPLLNLSLDLSLNPMNFIQPGAFKE    N   
3       1  O00206   282  EFRNEGNLEKFDKSALEGLCNLTIEEFRLAYLDYYLDDIID    N   
4       1  O00206   309  RLAYLDYYLDDIIDLFNCLTNVSSFSLVSVTIERVKDFSYN    N   
..    ...     ...   ...                                        ...  ...   
439     0  Q9Y572   514                  VGSQEGPKDPEAWSRPQGWYNHSGK    N   
440     0  Q9Y5C1    23  TIKLLLFIVPLVISSRIDQDNSSFDSLSPEPKSRFAMLDDV    N   
441     0  P35968   923  GACTKPGGPLMVIVEFCKFGNLSTYLRSKRNEFVPYKTKGA    N   
442     0  P35968  1256  VKTFEDIPLEEPEVKVIPDDNQTDSGMVLASEELKTLEDRT    N   
443     0  P35968  1300  PSFGGMVPSKSRESVASEGSNQTSGYQSGYHSDDTDTTVYS    N   

         5         6         7         8         9     ...      1019  \
0    0.003748 -0.110684 -0.153512 -0.018372  0.010009  ... -0.415227   
1   -0.199627 -0.017514 -0.225825  0.144699  0.180678  ... -0.294756   
2   -0.404316 -0.178852 -0.275003  0.122108  0.232455  ... -0.006435   
3   -0.207916 -0.133037 -0.198850 -0.006236  0.149640  ... -0.138576   
4   -0.230078 -0.268045 -0.119857  0.020648  0.175885  ... -0.291729   
..        ...       ...       ...       ...       ...  ...       ...   
439 -0.171356 -0.181110  0.010168 -0.377627  0.028843  ...  0.413291   
440 -0.143208  0.048386  0.081174  0.306305  0.117934  ... -0.189079   
441 -0.150947  0.281644 -0.149700 -0.446946  0.129487  ... -0.049990   
442  0.223785 -0.130943 -0.004928 -0.180788  0.166358  ...  0.161322   
443  0.375994  0.035225 -0.090608  0.039300  0.114250  ...  0.193061   

         1020      1021      1022      1023      1024      1025      1026  \
0   -0.266164  0.157757 -0.087011  0.061053 -0.449474 -0.071515  0.060078   
1   -0.279264  0.087897 -0.197072  0.176945 -0.194068 -0.190472  0.180533   
2    0.045456  0.071719  0.005021 -0.147672 -0.271382  0.023479  0.176901   
3   -0.196430  0.067653 -0.025049  0.093968 -0.181030 -0.195568  0.254518   
4    0.014870  0.031539 -0.119059  0.101250 -0.234652 -0.130318  0.256988   
..        ...       ...       ...       ...       ...       ...       ...   
439 -0.223393  0.006986 -0.167291  0.077375 -0.096225 -0.153087 -0.465871   
440 -0.160134 -0.121814 -0.047132  0.116614  0.184644  0.037888 -0.018008   
441 -0.108549 -0.233008 -0.002176  0.133184 -0.062494 -0.221085 -0.385398   
442 -0.346325 -0.094232 -0.049673  0.198314  0.033996  0.045103 -0.137851   
443 -0.359984 -0.053463 -0.037111  0.149048 -0.076953 -0.121076 -0.189793   

         1027      1028  
0    0.402396  0.253345  
1    0.451784  0.433823  
2    0.303784  0.089449  
3    0.609124  0.318503  
4    0.579983  0.334606  
..        ...       ...  
439 -0.437165 -0.016026  
440  0.411471  0.077139  
441  0.056123 -0.035016  
442  0.170921  0.187318  
443  0.030190  0.181636  

[444 rows x 1029 columns]

In [8]:
df_independent_testing.columns = ["Label","PID","Position","Peptide","ASN"]+[int(i) for i in range(1,1025)]

In [9]:
df_independent_testing

Label     PID  Position                                    Peptide ASN  \
0        1  O00206        35  MAFLSCVRPESWEPCVEVVPNITYQCMELNFYKIPDNLPFS   N   
1        1  O00206       173  KELNVAHNLIQSFKLPEYFSNLTNLEHLDLSSNKIQSIYCT   N   
2        1  O00206       205  NKIQSIYCTDLRVLHQMPLLNLSLDLSLNPMNFIQPGAFKE   N   
3        1  O00206       282  EFRNEGNLEKFDKSALEGLCNLTIEEFRLAYLDYYLDDIID   N   
4        1  O00206       309  RLAYLDYYLDDIIDLFNCLTNVSSFSLVSVTIERVKDFSYN   N   
..     ...     ...       ...                                        ...  ..   
439      0  Q9Y572       514                  VGSQEGPKDPEAWSRPQGWYNHSGK   N   
440      0  Q9Y5C1        23  TIKLLLFIVPLVISSRIDQDNSSFDSLSPEPKSRFAMLDDV   N   
441      0  P35968       923  GACTKPGGPLMVIVEFCKFGNLSTYLRSKRNEFVPYKTKGA   N   
442      0  P35968      1256  VKTFEDIPLEEPEVKVIPDDNQTDSGMVLASEELKTLEDRT   N   
443      0  P35968      1300  PSFGGMVPSKSRESVASEGSNQTSGYQSGYHSDDTDTTVYS   N   

            1         2         3         4         5  ...      1015  \
0    0.003748 -0.110684 -0.153512 -0.018372  0.010009  ... -0.415227   
1   -0.199627 -0.017514 -0.225825  0.144699  0.180678  ... -0.294756   
2   -0.404316 -0.178852 -0.275003  0.122108  0.232455  ... -0.006435   
3   -0.207916 -0.133037 -0.198850 -0.006236  0.149640  ... -0.138576   
4   -0.230078 -0.268045 -0.119857  0.020648  0.175885  ... -0.291729   
..        ...       ...       ...       ...       ...  ...       ...   
439 -0.171356 -0.181110  0.010168 -0.377627  0.028843  ...  0.413291   
440 -0.143208  0.048386  0.081174  0.306305  0.117934  ... -0.189079   
441 -0.150947  0.281644 -0.149700 -0.446946  0.129487  ... -0.049990   
442  0.223785 -0.130943 -0.004928 -0.180788  0.166358  ...  0.161322   
443  0.375994  0.035225 -0.090608  0.039300  0.114250  ...  0.193061   

         1016      1017      1018      1019      1020      1021      1022  \
0   -0.266164  0.157757 -0.087011  0.061053 -0.449474 -0.071515  0.060078   
1   -0.279264  0.087897 -0.197072  0.176945 -0.194068 -0.190472  0.180533   
2    0.045456  0.071719  0.005021 -0.147672 -0.271382  0.023479  0.176901   
3   -0.196430  0.067653 -0.025049  0.093968 -0.181030 -0.195568  0.254518   
4    0.014870  0.031539 -0.119059  0.101250 -0.234652 -0.130318  0.256988   
..        ...       ...       ...       ...       ...       ...       ...   
439 -0.223393  0.006986 -0.167291  0.077375 -0.096225 -0.153087 -0.465871   
440 -0.160134 -0.121814 -0.047132  0.116614  0.184644  0.037888 -0.018008   
441 -0.108549 -0.233008 -0.002176  0.133184 -0.062494 -0.221085 -0.385398   
442 -0.346325 -0.094232 -0.049673  0.198314  0.033996  0.045103 -0.137851   
443 -0.359984 -0.053463 -0.037111  0.149048 -0.076953 -0.121076 -0.189793   

         1023      1024  
0    0.402396  0.253345  
1    0.451784  0.433823  
2    0.303784  0.089449  
3    0.609124  0.318503  
4    0.579983  0.334606  
..        ...       ...  
439 -0.437165 -0.016026  
440  0.411471  0.077139  
441  0.056123 -0.035016  
442  0.170921  0.187318  
443  0.030190  0.181636  

[444 rows x 1029 columns]

In [10]:
df_independent_testing["Label"].value_counts()

0    278
1    166
Name: Label, dtype: int64

In [11]:
X_train = np.array(df_training.drop(["Label","PID","Position","Peptide","ASN"], axis=1))

In [12]:
X_train

array([[-0.29912701, -0.1995486 , -0.17985581, ...,  0.05002616,
         0.54556292,  0.30357531],
       [-0.09135242, -0.03851908, -0.0571196 , ...,  0.21440715,
         0.49502024,  0.10573006],
       [-0.30790338, -0.09298988, -0.17667472, ...,  0.40513539,
         0.40184912,  0.37338147],
       ...,
       [-0.09829833,  0.07039663, -0.09482615, ...,  0.16570042,
         0.26988527,  0.30127075],
       [-0.16042761,  0.11241627, -0.30247721, ...,  0.40895495,
         0.32904446,  0.21226849],
       [-0.18608511, -0.24441549,  0.12703583, ...,  0.15542366,
         0.11903537,  0.06460416]])

In [13]:
y_train = np.array(df_training["Label"])

In [14]:
y_train

array([1, 1, 1, ..., 0, 0, 0])

In [15]:
X_independent = np.array(df_independent_testing.drop(["Label","PID","Position","Peptide","ASN"], axis=1))

In [16]:
X_independent

array([[ 0.00374775, -0.1106843 , -0.15351185, ...,  0.06007803,
         0.40239587,  0.25334457],
       [-0.19962737, -0.01751441, -0.22582453, ...,  0.18053311,
         0.45178351,  0.43382293],
       [-0.40431601, -0.17885162, -0.27500263, ...,  0.17690088,
         0.30378446,  0.0894485 ],
       ...,
       [-0.15094724,  0.28164449, -0.14969961, ..., -0.38539818,
         0.05612256, -0.03501561],
       [ 0.2237853 , -0.13094278, -0.00492752, ..., -0.13785097,
         0.17092127,  0.18731776],
       [ 0.37599355,  0.03522549, -0.09060771, ..., -0.18979339,
         0.03019028,  0.18163587]])

In [17]:
y_independent = np.array(df_independent_testing["Label"])

In [18]:
y_independent

array([1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,

In [19]:
from imblearn.under_sampling import RandomUnderSampler
from sklearn.utils import shuffle
from sklearn.model_selection import train_test_split
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout, Flatten, Reshape, Lambda
from tensorflow.keras.layers import Conv2D, MaxPooling2D, Conv1D, MaxPooling1D
from sklearn.metrics import confusion_matrix
from sklearn.metrics import matthews_corrcoef
from sklearn.metrics import accuracy_score

2025-03-26 08:41:05.817911: I tensorflow/core/util/port.cc:104] oneDNN custom operations are on. You may see slightly different numerical results due to floating-point round-off errors from different computation orders. To turn them off, set the environment variable `TF_ENABLE_ONEDNN_OPTS=0`.


# Construct ANN

In [20]:
rus = RandomUnderSampler(random_state=4)
X_train, y_train = rus.fit_resample(X_train, y_train)
print()
print(X_train.shape, y_train.shape)
print()
X_train, y_train = shuffle(X_train, y_train, random_state=4)

x_train, x_val, y_train_1, y_val = train_test_split(X_train, y_train,random_state =4, test_size=0.1)

y_train_1 = tf.keras.utils.to_categorical(y_train_1,2)
y_val = tf.keras.utils.to_categorical(y_val,2)


model = Sequential()
model.add(Dense(64, input_dim=1024, kernel_initializer='uniform', activation="relu"))
model.add(Dropout(0.3))
model.add(Dense(2, activation="softmax"))


model.compile(optimizer=tf.keras.optimizers.Adam(),loss="binary_crossentropy",metrics=["accuracy"])

checkpointer = tf.keras.callbacks.ModelCheckpoint(filepath="ROC_ROC_Premise_Assumption.h5", 
                                monitor = 'val_accuracy',
                                verbose=0, 
                                save_weights_only=False,
                                save_best_only=True)

reduce_lr_acc = tf.keras.callbacks.ReduceLROnPlateau(monitor='val_accuracy', factor=0.001, patience=5, verbose=1, min_delta=1e-4, mode='max')

early_stopping = tf.keras.callbacks.EarlyStopping(monitor='val_accuracy',patience=5,mode='max')

history = model.fit(x_train, y_train_1,epochs=400,verbose=1,batch_size=256,
                        callbacks=[checkpointer,reduce_lr_acc, early_stopping],validation_data=(x_val, y_val))



print(X_independent.shape,y_independent.shape)

yval = y_independent

Y_pred = model.predict(X_independent)
Y_pred = (Y_pred > 0.5)
y_pred = [np.argmax(y, axis=None, out=None) for y in Y_pred]
y_pred = np.array(y_pred)

confusion = confusion_matrix(yval,y_pred)

print("Matthews Correlation : ",matthews_corrcoef(y_independent, y_pred))
print("Confusion Matrix : \n",confusion_matrix(y_independent, y_pred))
print("Accuracy on test set:   ",accuracy_score(y_independent, y_pred))

cm = confusion_matrix(y_independent, y_pred)

TP = cm[1][1]
TN = cm[0][0]
FP = cm[0][1]
FN = cm[1][0]

mcc = matthews_corrcoef(y_independent, y_pred)

Sensitivity = TP/(TP+FN)

Specificity = TN/(TN+FP)

print("Sensitivity:   ",Sensitivity,"\t","Specificity:   ",Specificity)


(1802, 1024) (1802,)

Epoch 1/400
7/7 [==============================] - 1s 39ms/step - loss: 0.5956 - accuracy: 0.7316 - val_loss: 0.5110 - val_accuracy: 0.8011 - lr: 0.0010
Epoch 2/400
7/7 [==============================] - 0s 26ms/step - loss: 0.4831 - accuracy: 0.7921 - val_loss: 0.4498 - val_accuracy: 0.8066 - lr: 0.0010
Epoch 3/400
7/7 [==============================] - 0s 26ms/step - loss: 0.4402 - accuracy: 0.7977 - val_loss: 0.4272 - val_accuracy: 0.8122 - lr: 0.0010
Epoch 4/400
7/7 [==============================] - 0s 4ms/step - loss: 0.4206 - accuracy: 0.8051 - val_loss: 0.4166 - val_accuracy: 0.8122 - lr: 0.0010
Epoch 5/400
7/7 [==============================] - 0s 4ms/step - loss: 0.4064 - accuracy: 0.8081 - val_loss: 0.4109 - val_accuracy: 0.8122 - lr: 0.0010
Epoch 6/400
7/7 [==============================] - 0s 4ms/step - loss: 0.3961 - accuracy: 0.8137 - val_loss: 0.4061 - val_accuracy: 0.8122 - lr: 0.0010
Epoch 7/400
7/7 [==============================] - 0s 23ms/ste