**Question 1**

In [1]:
import numpy as np

#Create a dictionary that maps each amino acid to an integer
aminoList = "ACDEFGHIKLMNPQRSTVWY"
aminoDict = {amino: i for i, amino in enumerate(aminoList)}
aminoDict

#Function that one-hot encodes a sequence
def one_hot_encode(sequence, aminoDict = aminoDict):
    #Create a matrix of zeros
    one_hot = np.zeros((len(sequence), len(aminoDict)))
    #Set the appropriate elements to 1
    for i, amino in enumerate(sequence):
        one_hot[i, aminoDict[amino]] = 1

    #Return the one-hot encoded sequence
    return one_hot

sequence = 'ACDGKINWE'
one_hot = one_hot_encode(sequence)
print(one_hot)

[[1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 0.]
 [0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]]


One Hot Encoding:

Pros:
- Effective for many machine learning algorithms
- Maintains disctinction between different categorical variables

Cons:
- High dimensionality(large vectors/matrices for many variables)
- High memory usage(for large datasets)

**Question 2**

In [32]:
import numpy as np 
import pandas as pd
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.feature_extraction.text import CountVectorizer

df = pd.DataFrame({'text':['students study materialx','materialx study materialx','students read materialx','materialx read note'],'output':[1,1,0,0]})

cv = CountVectorizer()
X_tf = cv.fit_transform(df['text']).toarray()
X_tf = X_tf/3
X_tf = pd.DataFrame(X_tf,columns=tokens,index=['doc0','doc1','doc2','doc3'])
print('Term Frequency: ')
X_tf

Term Frequency: 


materialx      note      read  students     study
doc0   0.333333  0.000000  0.000000  0.333333  0.333333
doc1   0.666667  0.000000  0.000000  0.000000  0.333333
doc2   0.333333  0.000000  0.333333  0.333333  0.000000
doc3   0.333333  0.333333  0.333333  0.000000  0.000000

In [33]:
tfidf = TfidfVectorizer()
X = tfidf.fit_transform(df['text']).toarray()
X = pd.DataFrame(X,columns=tokens,index=['doc0','doc1','doc2','doc3'])
tokens = list(tfidf.get_feature_names_out())
print(tokens)
print()
print('Inverse Document Frequency:',tfidf.idf_)
print()
print('TF-IDF: ')
X

['materialx', 'note', 'read', 'students', 'study']

Inverse Document Frequency: [1.         1.91629073 1.51082562 1.51082562 1.51082562]

TF-IDF: 


materialx      note      read  students     study
doc0   0.423897  0.000000  0.000000  0.640434  0.640434
doc1   0.797922  0.000000  0.000000  0.000000  0.602761
doc2   0.423897  0.000000  0.640434  0.640434  0.000000
doc3   0.379192  0.726641  0.572892  0.000000  0.000000

TF-IDF:

Pros:
- Used in information retrieval system

Cons:
- Sparsity
- Out of vocabulary words
- Large Dimensionality
- Semantic relation between words are not captured